import { configureFonts, MD3Colors } from 'react-native-paper';
import type { AppTheme } from '../types/theme';
import { MD3Typescale, MD3Type } from 'react-native-paper/lib/typescript/types';

const fontConfig: Partial<Record<keyof MD3Typescale, MD3Type>> = {
        titleMedium: {
            fontFamily: 'System',
            fontWeight: "600",
            fontSize: 20,
            lineHeight: 28,
            letterSpacing: 0,
        },
        bodyMedium: {
            fontFamily: 'System',
            fontWeight: "400",
            fontSize: 16,
            lineHeight: 24,
            letterSpacing: 0,
        },
        displayLarge: {
            fontFamily: 'System',
            fontWeight: "400",
            fontSize: 57,
            lineHeight: 64,
            letterSpacing: 0,
        },
        displayMedium: {
            fontFamily: 'System',
            fontWeight: "400",
            fontSize: 45,
            lineHeight: 52,
            letterSpacing: 0,
        },
        displaySmall: {
            fontFamily: 'System',
            fontWeight: "400",
            fontSize: 36,
            lineHeight: 44,
            letterSpacing: 0,
        },
        headlineLarge: {
            fontFamily: 'System',
            fontWeight: "400",
            fontSize: 32,
            lineHeight: 40,
            letterSpacing: 0,
        },
        headlineMedium: {
            fontFamily: 'System',
            fontWeight: "400",
            fontSize: 28,
            lineHeight: 36,
            letterSpacing: 0,
        },
        headlineSmall: {
            fontFamily: 'System',
            fontWeight: "400",
            fontSize: 24,
            lineHeight: 32,
            letterSpacing: 0,
        },
        titleLarge: {
            fontFamily: 'System',
            fontWeight: "400",
            fontSize: 22,
            lineHeight: 28,
            letterSpacing: 0,
        },
        titleSmall: {
            fontFamily: 'System',
            fontWeight: "500",
            fontSize: 14,
            lineHeight: 20,
            letterSpacing: 0.1,
        },
        bodyLarge: {
            fontFamily: 'System',
            fontWeight: "400",
            fontSize: 16,
            lineHeight: 24,
            letterSpacing: 0.5,
        },
        bodySmall: {
            fontFamily: 'System',
            fontWeight: "400",
            fontSize: 12,
            lineHeight: 16,
            letterSpacing: 0.4,
        },
        labelLarge: {
            fontFamily: 'System',
            fontWeight: "500",
            fontSize: 14,
            lineHeight: 20,
            letterSpacing: 0.1,
        },
        labelMedium: {
            fontFamily: 'System',
            fontWeight: "500",
            fontSize: 12,
            lineHeight: 16,
            letterSpacing: 0.5,
        },
        labelSmall: {
            fontFamily: 'System',
            fontWeight: "500",
            fontSize: 11,
            lineHeight: 16,
            letterSpacing: 0.5,
        },
};

export const theme: AppTheme = {
  version: 3 as const,
  isV3: true,
  colors: {
    primary: '#36618E',
    onPrimary: '#FFFFFF',
    primaryContainer: '#D1E4FF',
    onPrimaryContainer: '#001D36',
    secondary: '#6B538C',
    onSecondary: '#FFFFFF',
    background: '#F8F9FF',
    surface: '#F9F9FF',
    surfaceVariant: '#DBE4E6',
    error: '#B00020',
    onError: '#FFFFFF',
    errorContainer: '#F9DEDC',
    onErrorContainer: '#410002',
    outline: '#79747E',
    secondaryContainer: '#E8DEF8',
    onSecondaryContainer: '#21005D',
    tertiary: '#7D5260',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#FFD8E4',
    onTertiaryContainer: '#31111D',
    outlineVariant: '#CAC4D0',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#2F3033',
    inverseOnSurface: '#F1F0F4',
    inversePrimary: '#9ECAFF',
    surfaceDisabled: 'rgba(28, 27, 31, 0.12)',
    onSurfaceDisabled: 'rgba(28, 27, 31, 0.38)',
    backdrop: 'rgba(45, 48, 56, 0.4)',
    onSurface: '#1C1B1F',
    onSurfaceVariant: '#49454F',
    onBackground: '#1C1B1F',
    elevation: {
      level0: 'transparent',
      level1: '#F7F2FA',
      level2: '#F0F0F0', // Was using this one
      level3: '#E7E0EC',
      level4: '#E3DDE9',
      level5: '#DFDAE7',
    }
  },
  spacing: {
    tiny: 4,
    small: 8,
    medium: 16,
    large: 24,
  },
  roundness: 8,
  fonts: configureFonts({ config: fontConfig }) as any, // Type assertion as a workaround
  shape: {
    borderRadius: 8,
  },
  chartColors: {
    grid: '#CCCCCC',
    area: '#D1E4FF',
    point: '#36618E',
    progress: {
      active: '#36618E',
      inactive: '#D1E4FF',
    },
  },
  moodColors: {
    peace: '#A8E6CF',
    joy: '#F8D568',
    love: '#FFB6C1',
    reason: '#BDB2FF',
    acceptance: '#AED9E0',
  },
  animation: {
    scale: 1.0, // You can adjust this value if needed
  },
  dark: false,
  scaleFont: (size: number) => size,
  scaleSize: (size: number) => size,
};
